### ISSUE TITLE
KDE Plasma 5.20.5 halts when viewing minimap

### ISSUE THREAD

**Issue by hammk** [AxioDL/metaforce#366]
**(6%, can hold 10 missiles, first level of Morph ball)**
### A minute or two after loading a save file, I am prompted to open the minimap. When I do, I am given a world map. When I try to zoom back into the normal map by pushing Enter, my PC freezes.
![20210205_193952](https://user-images.githubusercontent.com/67597830/107105146-75206e80-67ea-11eb-9f84-d19047187551.jpg)
Prompt to open minimap.
![20210205_194019](https://user-images.githubusercontent.com/67597830/107105130-6afe7000-67ea-11eb-8b99-568bdb3adf8f.jpg)
Exact moment it freezes.

**Comment by encounter** [comment]
This may be resolved by 732831de9a9adbd138f9a7f954d4c3845ae49321, which reverts a commit that caused heap memory corruption.

**Comment by Antidote** [comment]
I'm pretty sure I fixed that with 087bd51, if you could test that branch for me and let me know if it does indeed fix it I'll go ahead and merge that branch into master.

**Comment by Antidote** [comment]
Actually, I believe the real cause is in the hint system, I'm going to look through it and make sure our code is correct.

**Comment by tomlube** [comment]
It's no longer a soft lock, but it still fails to navigate to another world correctly. progress :)

**Comment by Antidote** [comment]
At least that bug is squashed.

**Comment by tomlube** [comment]
@Antidote close this because it's fixed now? :)
