### ISSUE TITLE
Rumble is not released under certain conditions 

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#461]
https://user-images.githubusercontent.com/4616948/183788213-4276a169-498e-4b7e-b2b4-d7113edf0c24.mp4

lmao you're welcome for finding more and more insane stuff

**Comment by tomlube** [comment]
Fixed on Reborn.

**Comment by Antidote** [comment]
This can still happen on crash if the rumble motor is going, we'll need to have an on-exit hook to force motors off, not sure if that's an aurora responsibility or a client side responsibility.
